spring.application.name=placement-management-system

spring.datasource.url=jdbc:mysql://localhost:3306/campus_placement
spring.datasource.username=root
spring.datasource.password=Mani#27059090

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true